proxy:
  # Master switch
  enabled: false

  # Examples (depending on environment):
  # http:  socks5h://127.0.0.1:9050
  # https: socks5h://127.0.0.1:9050
  # "http":  "socks5h://torproxy:9050",
  # "https": "socks5h://torproxy:9050",
  http:
  https:
